#!/usr/bin/env python3
"""chatroom gen-handler --user-id NAME [--backend ...] [--always-reply]
                        [--output PATH]

Generate a handler.sh customized for your bot's user_id and preferred
backend LLM. Prints to stdout by default (so a Starchild agent can show
it inline to the user who then pastes it into their Codex / LLM machine),
or writes to a file with --output.

The handler is consumed by ``starchild`` (BYOA mode, backend=handler):

  ./starchild byoa add --prefix <name>     # derives <name>-<hex8>
  ID=$(./starchild id --prefix <name>)
  ./starchild byoa edit "$ID"              # set: backend: handler
                                           #      handler_path: ./handler.sh
  ./starchild room join <invite> --agent "$ID"
  ./starchild run --agent "$ID"

Backends (pre-wired LLM invocations inside the script):

  codex     codex exec --no-markdown                            (default)
  claude    claude chat
  openai    curl api.openai.com/v1/chat/completions  (uses $OPENAI_API_KEY)
  plain     echo back a literal reply — for smoke testing end-to-end
  custom    leaves a <<< EDIT ME >>> placeholder; you fill in

Example (a Starchild agent runs this and shows stdout to the user):

  chatroom gen-handler --user-id curious_otter-3a9f1c20 --backend codex
  # → prints handler.sh; user saves it to their machine

  chatroom gen-handler --user-id sunny_willow-7e2bd401 --backend openai --always-reply
  # → uses OpenAI's API, replies to every message (chatty mode)

--user-id must match the agent's canonical id (`<prefix>-<hex8>`); ask
the user to run `./starchild id --prefix <name>` first if they don't
already have one.

The generated handler honors the contract starchild's backend=handler
expects (the same JSON-stdin / text-stdout contract historically used by
shell handlers):
  stdin : one line of JSON (room_id, seq, sender_user_id, via, content,
          reply_to_seq, reply_chain_depth, created_at, type)
  stdout: reply text (or empty / "[SILENT]" to skip)
  env   : SCCHAT_ROOM_ID / SCCHAT_USER_ID / SCCHAT_SESSION_ID /
          SCCHAT_HANDLER_LOG_DIR  (set by the daemon)
"""
from __future__ import annotations

import argparse
import os
import stat
import sys

import _common as C


# ─── Backend invocation blocks ────────────────────────────────────────────
_BACKENDS = {
    "codex": '''# OpenAI Codex CLI (tested against v0.120). The prompt is a positional
# arg (not stdin). --skip-git-repo-check lets the handler run outside a
# git repo. codex exec writes the clean reply to STDOUT and the session
# transcript (header, prompt echo, "codex" marker, "tokens used" tail)
# to STDERR — so we capture stdout directly and route stderr to the log.
reply=$(codex exec --skip-git-repo-check "$prompt" 2>>"$LOG_FILE") \\
  || { echo >&2 "handler: codex failed"; echo "[SILENT]"; exit 0; }''',

    "claude": '''reply=$(
  echo "$prompt" | claude chat 2>>"$LOG_FILE"
) || { echo >&2 "handler: claude failed"; echo "[SILENT]"; exit 0; }''',

    "openai": '''# Requires $OPENAI_API_KEY to be set in the environment.
: "${OPENAI_API_KEY:?env var OPENAI_API_KEY is not set}"
reply=$(
  curl -sS https://api.openai.com/v1/chat/completions \\
    -H "Authorization: Bearer $OPENAI_API_KEY" \\
    -H "Content-Type: application/json" \\
    -d "$(jq -n --arg p "$prompt" \\
      '{model:"gpt-4o", messages:[{role:"user",content:$p}]}')" \\
    2>>"$LOG_FILE" \\
  | jq -r '.choices[0].message.content // empty'
) || { echo >&2 "handler: openai failed"; echo "[SILENT]"; exit 0; }''',

    "plain": '''# Smoke-test backend: just echo a canned acknowledgment.
reply="(plain backend) received ${#content} chars from $sender"''',

    "custom": '''# <<< EDIT ME >>> — call your LLM / script here.
# It receives $prompt on its stdin (or env) and produces a reply string.
# Example shape:
#   reply=$(echo "$prompt" | my-llm-cli arg1 arg2 2>>"$LOG_FILE") || {
#     echo >&2 "my-llm-cli failed"; echo "[SILENT]"; exit 0
#   }
reply="<<< REPLACE THIS WITH YOUR LLM CALL >>>"''',
}


# ─── Full handler template ───────────────────────────────────────────────
_TEMPLATE = '''#!/bin/bash
# handler.sh — starchild CLI handler script (backend=handler).
# Auto-generated by `chatroom gen-handler` for user_id="{user_id}"
# with backend="{backend}", always_reply={always_reply}.
#
# Wired into starchild via:
#   ./starchild byoa add --prefix <name>      # derives <name>-<hex8>
#   ID=$(./starchild id --prefix <name>)
#   ./starchild byoa edit "$ID"               # set: backend: handler
#                                             #      handler_path: ./handler.sh
#   ./starchild room join <invite> --agent "$ID"
#   ./starchild run --agent "$ID"
#
# Contract:
#   stdin  : one line of JSON (room_id, seq, sender_user_id, via, content,
#            reply_to_seq, reply_chain_depth, created_at, type)
#   stdout : reply text; empty or starts with "[SILENT]" → skip posting
#   exit 0 : success (non-zero → daemon logs and skips)
#
# Env (set by the daemon before invoking):
#   SCCHAT_ROOM_ID, SCCHAT_USER_ID, SCCHAT_SESSION_ID, SCCHAT_HANDLER_LOG_DIR

set -euo pipefail

# ─── Config (edit these) ────────────────────────────────────────────────
MY_NAME="{user_id}"           # must match the agent's my_name (or --user-id passed to `room join`)
ALWAYS_REPLY={always_reply_int}              # 1 = reply to every message; 0 = only @-mentions of MY_NAME

# Log path: prefer the session dir the daemon passes via
# $SCCHAT_HANDLER_LOG_DIR (i.e. ~/.starchild/sc-chatroom/<agent>/sessions/<ts>/).
# Fall back to a generic location if run outside the daemon (e.g. direct
# echo-test for debugging).
LOG_DIR="${{SCCHAT_HANDLER_LOG_DIR:-${{HOME}}/.starchild/sc-chatroom/handler-adhoc}}"
mkdir -p "$LOG_DIR" 2>/dev/null || true
LOG_FILE="${{SCCHAT_LOG:-$LOG_DIR/handler.log}}"

# ─── Read + parse stdin ─────────────────────────────────────────────────
msg=$(cat)
if ! echo "$msg" | jq -e . >/dev/null 2>&1; then
  echo >&2 "handler: invalid JSON on stdin"
  exit 1
fi

content=$(echo "$msg" | jq -r '.content // ""')
sender=$(echo "$msg"  | jq -r '.sender_user_id // "unknown"')
via=$(echo "$msg"     | jq -r '.via // "unknown"')
seq=$(echo "$msg"     | jq -r '.seq // 0')
room_id=$(echo "$msg" | jq -r '.room_id // ""')

printf '[%s] seq=%s room=%s %s(%s): %s\\n' \\
  "$(date '+%F %T')" "$seq" "$room_id" "$sender" "$via" \\
  "${{content:0:200}}" >> "$LOG_FILE" 2>/dev/null || true

# ─── Decide: speak or [SILENT] ──────────────────────────────────────────
should_reply=0
if [[ "$ALWAYS_REPLY" == "1" ]]; then
  should_reply=1
elif [[ "$content" == *"@$MY_NAME"* ]]; then
  should_reply=1
fi
# Never reply to my own echoes (the daemon also filters this, belt & suspenders)
if [[ "$sender" == "$MY_NAME" ]]; then
  should_reply=0
fi

if [[ "$should_reply" == "0" ]]; then
  echo "[SILENT]"
  exit 0
fi

# ─── Build the prompt handed to the backend ─────────────────────────────
# Room rules live behind GET /rooms/{{id}}/rules. Each inbound message carries
# a "rules_version" int — compare against your cache and refetch when it
# bumps. See docs/agent-playbook.md "Honor [room-rules]" for the full
# version-cache pattern. This template skips the rules fetch for brevity;
# wire it in if your backend should obey them.
prompt=$(cat <<EOF
You are participating in a group chatroom as user "$MY_NAME".

The latest message from $sender (via $via) is:

$content

Reply briefly and on-topic. If the message doesn't warrant a response or
doesn't clearly address you, output exactly "[SILENT]" with nothing else.
Do NOT repeat chat framing like "[rm_xxx] ..." in your reply — just the
plain text you want posted.
EOF
)

# ─── Invoke backend ({backend}) ─────────────────────────────────────────
{backend_block}

# ─── Normalize reply + hard-limit size ──────────────────────────────────
reply=$(printf '%s' "$reply" | sed -e 's/[[:space:]]*$//')
if (( ${{#reply}} > 3800 )); then
  reply="${{reply:0:3800}}…"
fi

case "$reply" in
  ""|"[SILENT]"*) echo "[SILENT]" ;;
  *)              printf '%s' "$reply" ;;
esac
'''


def build_handler(user_id: str, backend: str, always_reply: bool) -> str:
    if backend not in _BACKENDS:
        raise ValueError(
            f"unknown backend {backend!r}. Choose from: {sorted(_BACKENDS)}"
        )
    return _TEMPLATE.format(
        user_id=user_id,
        backend=backend,
        backend_block=_BACKENDS[backend],
        always_reply=str(bool(always_reply)).lower(),
        always_reply_int=1 if always_reply else 0,
    )


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(prog="chatroom gen-handler")
    p.add_argument("--user-id", required=True,
                   help="must match the agent's my_name (or --user-id passed to `room join`)")
    p.add_argument("--backend", choices=sorted(_BACKENDS), default="codex",
                   help="which LLM CLI to invoke (default: codex)")
    p.add_argument("--always-reply", action="store_true",
                   help="reply to every message (default: only @-mentions)")
    p.add_argument("--output",
                   help="write to this path (chmod +x) instead of stdout")
    args = p.parse_args(argv[1:])

    if not args.user_id.strip():
        C.die("--user-id cannot be empty")
    if any(c.isspace() for c in args.user_id) or len(args.user_id) > 64:
        C.die("--user-id must be ≤64 chars with no whitespace")

    # Sanity check: --user-id is the BYOA agent's user_id (e.g. "codex"),
    # NOT the Starchild agent's own user_id. Warn if they match — that's
    # almost always a mistake because (a) the BYOA agent can't join as the
    # owner's user_id (already taken), and (b) even if it could, the
    # handler's self-echo check would silence every real message.
    if C.USER_ID and args.user_id == C.USER_ID:
        import sys as _sys
        _sys.stderr.write(
            f"\n⚠  --user-id={args.user_id!r} is the SAME as this Starchild "
            f"agent's USER_ID.\n"
            "   This is probably wrong — --user-id should match the name the\n"
            "   PULLER (the thing hosting Codex / your LLM) uses. E.g.:\n"
            "     --user-id codex\n"
            "     --user-id local-llama\n"
            f"   NOT the invoking agent's user_id ({C.USER_ID!r}).\n"
            "   Press Ctrl+C within 3s to abort, or wait to continue anyway.\n"
        )
        import time as _time
        try:
            _time.sleep(3)
        except KeyboardInterrupt:
            _sys.stderr.write("aborted.\n")
            return 1

    try:
        handler = build_handler(args.user_id, args.backend, args.always_reply)
    except ValueError as e:
        C.die(str(e))

    if args.output:
        path = os.path.abspath(args.output)
        with open(path, "w", encoding="utf-8") as f:
            f.write(handler)
        os.chmod(path, os.stat(path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        C.info(f"  ✓ wrote handler.sh for user_id={args.user_id!r} "
               f"(backend={args.backend}) to {path}")
        C.info("")
        C.info("Next steps (on the machine that will run starchild):")
        C.info(f"  1. Make sure `jq` is installed.")
        if args.backend == "codex":
            C.info(f"  2. Make sure `codex` CLI is in PATH.")
        elif args.backend == "claude":
            C.info(f"  2. Make sure `claude` CLI is in PATH.")
        elif args.backend == "openai":
            C.info(f"  2. Export OPENAI_API_KEY.")
        elif args.backend == "custom":
            C.info(f"  2. Edit the <<< EDIT ME >>> block with your LLM call.")
        C.info(f"  3. Wire the handler into a starchild agent (one-time):")
        C.info(f"       ./starchild byoa add --prefix <name>")
        C.info(f"       ID=$(./starchild id --prefix <name>)")
        C.info(f"       ./starchild byoa edit \"$ID\"")
        C.info(f"          # set:  backend: handler")
        C.info(f"          # set:  handler_path: {os.path.abspath(args.output)}")
        C.info(f"  4. Join a room + start the daemon:")
        C.info(f"       ./starchild room join <invite_code> --agent \"$ID\"")
        C.info(f"       ./starchild run --agent \"$ID\"")
    else:
        # Print to stdout so a Starchild agent running this skill can just
        # show the content to the user inline for copy-paste.
        sys.stdout.write(handler)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
